// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjEgfaT7brq4PDjff1-AF6f70jcOGY5yk',
    appId: '1:156287195411:android:386c257b57f71b938722e6',
    messagingSenderId: '156287195411',
    projectId: 'team-project-b7564',
    storageBucket: 'team-project-b7564.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaiYYxXLJMzOzrJ14e7qDCIVEN73N5xSM',
    appId: '1:156287195411:ios:e0c1705a581a67228722e6',
    messagingSenderId: '156287195411',
    projectId: 'team-project-b7564',
    storageBucket: 'team-project-b7564.firebasestorage.app',
    iosBundleId: 'com.example.teamManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBL7Zq2ZYnfcJCKKQ2Q5BFhJaGDJq_A0g',
    appId: '1:156287195411:web:b7077a326b6f471c8722e6',
    messagingSenderId: '156287195411',
    projectId: 'team-project-b7564',
    authDomain: 'team-project-b7564.firebaseapp.com',
    storageBucket: 'team-project-b7564.firebasestorage.app',
    measurementId: 'G-689QCJXET7',
  );
}
